modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="mc_color_clash"
version="0.0.1"
displayName="MC Color Clash"
logoFile="mc_color_clash.png"
credits="Thanks to Jesus"
authors="marcopiii"
description="A Forge 1.19 mod"
